version: '3.7'
services:
  web:
    build: .
    init: true
    command: yarn serve
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file: .env
    environment:
      NODE_ENV: development
    ports:
      - "8080:8080"
